services:
  findarr:
    image: ghcr.io/lillifee/findarr:latest
    restart: unless-stopped
    ports:
      - 8585:8585
    volumes:
      - findarr-data:/app/apps/server/data
      # - ./data:/app/apps/server/data
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=8585

volumes:
  findarr-data:
