services:
  app:
    image: ghcr.io/lillifee/findarr:latest
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: '8585'
    ports:
      - '8585:8585'
    restart: unless-stopped
    volumes:
      - findarr-data:/app/server/data

volumes:
  findarr-data:
