packages:
  - packages/*
  - apps/*

allowBuilds:
  better-sqlite3: true
  esbuild: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vitest: 4.1.10
  vite-plus: 0.2.6
  typescript: ^7.0.2

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  '@types/node': ^26.0.0

peerDependencyRules:
  allowAny:
    - vite
    - vitest

  allowedVersions:
    vite: '*'
    vitest: '*'
